/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : -- Unnamed --
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_FINDNEXT                            0
#define GD_QUITNEWSCAN                         1

#define GDX_FINDNEXT                           0
#define GDX_QUITNEWSCAN                        1

#define Project1_CNT 2

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *Project1Wnd;
extern struct Gadget        *Project1GList;
extern struct Gadget        *Project1Gadgets[2];
extern UWORD                 Project1Left;
extern UWORD                 Project1Top;
extern UWORD                 Project1Width;
extern UWORD                 Project1Height;
extern UBYTE                *Project1Wdt;
extern struct TextAttr      *Font, Attr;
extern UWORD                 FontX, FontY;
extern UWORD                 OffX, OffY;
extern UWORD                 Project1GTypes[];
extern struct NewGadget      Project1NGad[];
extern ULONG                 Project1GTags[];

extern void Project1Render( void );
extern int OpenProject1Window( void );
extern void CloseProject1Window( void );
