/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : -- Unnamed --
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_REAL                                0
#define GD_ALIAS                               1
#define GD_SAVE                                2
#define GD_SEARCH                              3
#define GD_QUIT                                4
#define GD_LOC                                 5
#define GD_PHONE                               6
#define GD_COMP                                7
#define GD_SBL                                 8
#define GD_SEC                                 9
#define GD_TIMELIMIT                           10
#define GD_TIMEUSED                            11
#define GD_PROTO                               12
#define GD_BYTESDOWN                           13
#define GD_BYTESUP                             14
#define GD_FILESDOWN                           15
#define GD_FILESUP                             16
#define GD_FIRSTCALL                           17
#define GD_LASTCALL                            18
#define GD_PREV                                19
#define GD_NEXT                                20
#define GD_PASS                                21
#define GD_CONFACCESS                          22
#define GD_SETS                                23
#define GD_FREEBYTES                           24
#define GD_FREEFILES                           25
#define GD_FILERATIO                           26
#define GD_BYTERATIO                           27
#define GD_NEWSCAN                             28
#define GD_DEL                                 29

#define GDX_REAL                               0
#define GDX_ALIAS                              1
#define GDX_SAVE                               2
#define GDX_SEARCH                             3
#define GDX_QUIT                               4
#define GDX_LOC                                5
#define GDX_PHONE                              6
#define GDX_COMP                               7
#define GDX_SBL                                8
#define GDX_SEC                                9
#define GDX_TIMELIMIT                          10
#define GDX_TIMEUSED                           11
#define GDX_PROTO                              12
#define GDX_BYTESDOWN                          13
#define GDX_BYTESUP                            14
#define GDX_FILESDOWN                          15
#define GDX_FILESUP                            16
#define GDX_FIRSTCALL                          17
#define GDX_LASTCALL                           18
#define GDX_PREV                               19
#define GDX_NEXT                               20
#define GDX_PASS                               21
#define GDX_CONFACCESS                         22
#define GDX_SETS                               23
#define GDX_FREEBYTES                          24
#define GDX_FREEFILES                          25
#define GDX_FILERATIO                          26
#define GDX_BYTERATIO                          27
#define GDX_NEWSCAN                            28
#define GDX_DEL                                29

#define Project0_CNT 30

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *Project0Wnd;
extern struct Gadget        *Project0GList;
extern struct Gadget        *Project0Gadgets[30];
extern UWORD                 Project0Left;
extern UWORD                 Project0Top;
extern UWORD                 Project0Width;
extern UWORD                 Project0Height;
extern UBYTE                *Project0Wdt;
extern struct TextAttr      *Font, Attr;
extern UWORD                 FontX, FontY;
extern UWORD                 OffX, OffY;
extern UWORD                 Project0GTypes[];
extern struct NewGadget      Project0NGad[];
extern ULONG                 Project0GTags[];


extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern void Project0Render( void );
extern int OpenProject0Window( void );
extern void CloseProject0Window( void );
